def hello(message):
    text = f"Hello {message.from_user.first_name}\! I\`m iVerbBot\."
    text += "I know something about irregular verbs\."
    text += "\n\n"
    text += "I have two states\.\n"
    text += "First state is the `self\-input state`\n"
    text += "You can send me any word and if it is a verb and it is irregular\n"
    text += "I\`ll send you back something useful\."
    text += "\n\n"
    text += "Second state is `quiz`\n"
    text += "Now, I\`ll send you the first form of an irregular verb\n"
    text += "And you should send me back a second form and the third form of that verb\n"
    text += "In this format \-\> `second_form`, `third_form` it\`s important\!\n"
    text += "\n\n"
    # text += "Also, I can send you `irregular verbs cheat\-sheet`\n"
    # text += "Just hit the `Gimme that sheet\!` button\.\n"
    # text += "\n\n"
    text += "If you noticed that something goes wrong\."
    text += "Feel free to text my owner @bmeupwork"
    return text